apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-deployment
  namespace: mern-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mern
  template:
    metadata:
      labels:
        app: mern
    spec:
      containers:
      - name: mern
        image: darshanpandya/mern:latest   # Jenkins will update to latest build
        ports:
        - containerPort: 3000

